sudo: false
language: cpp
matrix:
    include:
    - os: linux
      dist: trusty
    - os: osx 
      osx_image: xcode8
      osx_image: xcode7.2

#install:
#- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - zlib1g
    - zlib1g-dev
    - libboost-dev
    - libboost-system-dev
    - libboost-test-dev
    - libtbb-dev
 brew-packages:
    - tbb

notifications:
  email: false

script:
 - export LD_LIBRARY_PATH=$HOME/lib
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
 - ./configure --prefix=$HOME && make  && make install
 - make check
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make check; fi
 #For some reason, make check on OS X + conda fails to respect LD_LIBRARY_PATH,
 #so we'll run the tests manually
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd test; for i in $(find testsuite -type f -perm +111);do $i -r detailed;cd .. ;done; fi
 - $HOME/bin/libsequenceConfig --version
